In [34]:
import pandas as pd
import numpy as np

In [35]:
BED_FILE = "~/Documents/bioinformatics/data-simulation/real-data/curtis_testing.bed"
col_labels = ["chr", "start", "end", "uc", "mc", "prop"]
bed_data = pd.read_csv(BED_FILE, sep='\t', names=col_labels, header=None)

In [36]:
arr = bed_data["prop"].iloc[50:55].to_numpy()
print(arr)

[ 5.26315789 87.5        84.61538462 86.95652174  7.69230769]


In [37]:
d = np.diag(arr)
print(d)

[[ 5.26315789  0.          0.          0.          0.        ]
 [ 0.         87.5         0.          0.          0.        ]
 [ 0.          0.         84.61538462  0.          0.        ]
 [ 0.          0.          0.         86.95652174  0.        ]
 [ 0.          0.          0.          0.          7.69230769]]


In [38]:
arr = arr / 5
print(arr)

[ 1.05263158 17.5        16.92307692 17.39130435  1.53846154]


In [40]:
A = np.vstack((d, arr))
print(A)

[[ 5.26315789  0.          0.          0.          0.        ]
 [ 0.         87.5         0.          0.          0.        ]
 [ 0.          0.         84.61538462  0.          0.        ]
 [ 0.          0.          0.         86.95652174  0.        ]
 [ 0.          0.          0.          0.          7.69230769]
 [ 1.05263158 17.5        16.92307692 17.39130435  1.53846154]]


In [11]:
import pandas as pd
cols = ["A", "B", "C"]
df1 = pd.DataFrame([[1, 2, 3]], columns=cols)
df3 = pd.concat([df1, pd.DataFrame([[4, 5, 6]], columns=cols)], ignore_index=True)
print(df3)
print(df3.at[1, "B"])

   A  B  C
0  1  2  3
1  4  5  6
5


In [17]:
df3.loc[0:1, "B"] = df3.loc[0:1, "B"] * (1 + 0.5) 
print(df3)

   A       B  C
0  1   6.750  3
1  4  16.875  6


In [48]:
import numpy as np
rng = np.random.default_rng()
min_num = 0
max_num = 10
print(rng.random() * (max_num - min_num) + min_num) 

3.534336816705026


In [50]:
print(round(8.8))

9
8
