In [34]:
import pandas as pd
import numpy as np

In [35]:
BED_FILE = "~/Documents/bioinformatics/data-simulation/real-data/curtis_testing.bed"
col_labels = ["chr", "start", "end", "uc", "mc", "prop"]
bed_data = pd.read_csv(BED_FILE, sep='\t', names=col_labels, header=None)

In [36]:
arr = bed_data["prop"].iloc[50:55].to_numpy()
print(arr)

[ 5.26315789 87.5        84.61538462 86.95652174  7.69230769]


In [37]:
d = np.diag(arr)
print(d)

[[ 5.26315789  0.          0.          0.          0.        ]
 [ 0.         87.5         0.          0.          0.        ]
 [ 0.          0.         84.61538462  0.          0.        ]
 [ 0.          0.          0.         86.95652174  0.        ]
 [ 0.          0.          0.          0.          7.69230769]]


In [38]:
arr = arr / 5
print(arr)

[ 1.05263158 17.5        16.92307692 17.39130435  1.53846154]


In [40]:
A = np.vstack((d, arr))
print(A)

[[ 5.26315789  0.          0.          0.          0.        ]
 [ 0.         87.5         0.          0.          0.        ]
 [ 0.          0.         84.61538462  0.          0.        ]
 [ 0.          0.          0.         86.95652174  0.        ]
 [ 0.          0.          0.          0.          7.69230769]
 [ 1.05263158 17.5        16.92307692 17.39130435  1.53846154]]


In [11]:
import pandas as pd
cols = ["A", "B", "C"]
df1 = pd.DataFrame([[1, 2, 3]], columns=cols)
df3 = pd.concat([df1, pd.DataFrame([[4, 5, 6]], columns=cols)], ignore_index=True)
print(df3)
print(df3.at[1, "B"])

   A  B  C
0  1  2  3
1  4  5  6
5


In [17]:
df3.loc[0:1, "B"] = df3.loc[0:1, "B"] * (1 + 0.5) 
print(df3)

   A       B  C
0  1   6.750  3
1  4  16.875  6


In [64]:
import numpy as np
rng = np.random.default_rng()
min_num = 0.4 
max_num = 0.7
print(100 * (rng.random() * (max_num - min_num) + min_num))

67.62670239634127


In [66]:
print(round(8.8))

9


In [1]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)
df.at[0, 'Name'] = 'joe'
print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14
   Name  Age
0   joe   10
1  nick   15
2  juli   14


In [4]:
def my_func(a, b):
    return a + b

l = (1, 2)
print(my_func(*l))

3


In [8]:
num_regions_per_core = 100
num_cores = 8
region_ranges = [(i * num_regions_per_core, (i + 1) * num_regions_per_core - 1) for i in range(num_cores)]
print(region_ranges)
print(region_ranges[-1][1])
print(len([1, 2, 3]))

[(0, 99), (100, 199), (200, 299), (300, 399), (400, 499), (500, 599), (600, 699), (700, 799)]
799
3
